-- Adicionar campos de endereço, CPF e foto à tabela funcionarios
ALTER TABLE funcionarios
ADD COLUMN IF NOT EXISTS cpf VARCHAR(14),
ADD COLUMN IF NOT EXISTS tipo_pessoa VARCHAR(50) DEFAULT 'Usuário',
ADD COLUMN IF NOT EXISTS cep VARCHAR(9),
ADD COLUMN IF NOT EXISTS logradouro VARCHAR(255),
ADD COLUMN IF NOT EXISTS numero VARCHAR(10),
ADD COLUMN IF NOT EXISTS complemento VARCHAR(255),
ADD COLUMN IF NOT EXISTS bairro VARCHAR(100),
ADD COLUMN IF NOT EXISTS estado VARCHAR(2),
ADD COLUMN IF NOT EXISTS cidade VARCHAR(100),
ADD COLUMN IF NOT EXISTS foto_url TEXT;
